### ISSUE TITLE
Allow to specify the entire config

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-setup#10]
Instead of fidgeting with `release-channels`, I think we should just have a `config` field where the user can dump the entire config. Config values are all `Maybe`, so partial config is valid.

So you'd do something like:

```yaml
on: [push]
name: build
jobs:
  runhaskell:
    name: Hello World
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell/ghcup-setup@v1
        with:
          config:
            verbose: true
            url-source:
              - GHCupURL
              - cross
      - run: |
          ghcup install ghc --set latest
          runhaskell Hello.hs
```

Would that work?
